[package]
name = "01"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/move-stdlib", rev = "main" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/moveos-stdlib", rev = "main" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/rooch-framework", rev = "main" }

[addresses]
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
01 = "_"
01_local = "_"
01_dev = "_"
01_test = "_"
01_main = "_"

[dev-addresses]
01 = "0x42"
01_local = "0x43"
01_dev = "0x44"
01_test = "0x45"
01_main = "0x46"
