[package]
name = "nip_89"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/move-stdlib", rev = "main" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/moveos-stdlib", rev = "main" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/rooch-framework", rev = "main" }

[addresses]
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
# Smart contract addresses on each subnet of Rooch Network
# nip_89 is equal to nip_89_local
nip_89 = "_"
nip_89_dev = "_"
nip_89_test = "_"
nip_89_main = "_"

[dev-addresses]
# Smart contract dev addresses on each subnet of Rooch Network
# nip_89 is equal to nip_89_local
nip_89 = "0x42"
nip_89_dev = "0x43"
nip_89_test = "0x44"
nip_89_main = "0x45"
