[package]
name = "nip"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/move-stdlib", rev = "main" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/moveos-stdlib", rev = "main" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/rooch-framework", rev = "main" }

[addresses]
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
nip = "_"
nip_local = "_"
nip_dev = "_"
nip_test = "_"
nip_main = "_"

[dev-addresses]
nip = "0x42"
nip_local = "0x43"
nip_dev = "0x44"
nip_test = "0x45"
nip_main = "0x46"
